version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install pipenv
            pipenv install --python /usr/local/bin/python --dev
      - python/save-cache
      - run:
          name: Run pytest
          command: pipenv run test --username $USER_NAME --apikey $API_KEY --blogname $BLOG_NAME

workflows:
  main:
    jobs:
      - build-and-test:
          context:
            - LIVEDOOR_BLOG
