name: Upload Python Package

on: [push]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Run pytest
      env:
        USER_NAME: ${{ secrets.LIVEDOOR_USER_NAME }}
        API_KEY: ${{ secrets.LIVEDOOR_API_KEY }}
        BLOG_NAME: ${{ secrets.LIVEDOOR_BLOG_NAME }}
      run: |
       touch .env
       USER_NAME="$USER_NAME" >> .env
       API_KEY="$API_KEY" >> .env
       BLOG_NAME="$BLOG_NAME" >> .env
       pipenv run pytest
